### ISSUE TITLE
Issue at chapter01

### ISSUE THREAD

**Issue by OlegRasskazov** [deeleman/angular2-essentials#52] opened 2017-01-27 11:40 UTC
import bootstrap module doesn't work. I got error TS2305.
for a solution I have addressed to https://angular.io/docs/ts/latest/guide/ngmodule.html#!#bootstrap

**Comment by demr** [comment] 2017-01-31 02:38
Other:
>typings install es6-shim --ambient --save
typings ERR! deprecated The "ambient" flag is deprecated. Please use "global" instead

>typings install es6-shim --global --save
typings ERR! message Unable to find "es6-shim" ("npm") in the registry.
typings ERR! message However, we found "es6-shim" for 1 other source: "dt"
typings ERR! message You can install these using the "source" option.
typings ERR! message We could use your help adding these typings to the registry: https://github.com/typings/registry
typings ERR! caused by https://api.typings.org/entries/npm/es6-shim/versions/latest responded with 404, expected it to equal 200

Another way to do that? Is it necessary?

**Comment by deeleman** [comment] 2017-01-31 08:07
Thanks for pointing out a workaround for this @OlegRasskazov 

@demr Your issue is a dupe of #10

In any event, I'd advice you on installing typings from npm instead. You can find more info at:

https://blogs.msdn.microsoft.com/typescript/2016/06/15/the-future-of-declaration-files/

**Closed as completed by deeleman** 2017-01-31 08:07 UTC
