### ISSUE TITLE
$ typings install es6-shim --ambient --save  getting error even after changing to global

### ISSUE THREAD

**Issue by linuxgeeky** [deeleman/angular2-essentials#50] opened 2016-12-28 10:37 UTC
F:\MyWorkspaces\angular_workspace\learning_angular2>typings install es6-shim --ambient --save
typings ERR! deprecated The "ambient" flag is deprecated. Please use "global" instead

F:\MyWorkspaces\angular_workspace\learning_angular2>typings install es6-shim --global --save
typings ERR! message Unable to find "es6-shim" ("npm") in the registry.
typings ERR! message However, we found "es6-shim" for 1 other source: "dt"
typings ERR! message You can install these using the "source" option.
typings ERR! message We could use your help adding these typings to the registry: https://github.com/typings/registry
typings ERR! caused by https://api.typings.org/entries/npm/es6-shim/versions/latest responded with 404, expected it to equal 200
typings ERR!
typings ERR! cwd F:\MyWorkspaces\angular_workspace\learning_angular2
typings ERR! system Windows_NT 10.0.10586
typings ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\linuxgeek\\AppData\\Roaming\\npm\\node_modules\\typings\\dist\\bin.js" "install" "es6-shim" "--global" "--save"
typings ERR! node -v v6.9.1
typings ERR! typings -v 2.1.0
typings ERR!
typings ERR! If you need help, you may report this error at:
typings ERR!   <https://github.com/typings/typings/issues>

**Comment by deeleman** [comment] 2016-12-28 17:02
Dupe of #10

In any event, I'd advice you on installing typings from npm instead. You can find more info at:

https://blogs.msdn.microsoft.com/typescript/2016/06/15/the-future-of-declaration-files/

**Closed as completed by deeleman** 2016-12-28 17:02 UTC
