### ISSUE TITLE
typings install es6-shim --ambient--save doesn't work

### ISSUE THREAD

**Issue by ricardosotogar** [deeleman/angular2-essentials#47] opened 2016-12-19 00:36 UTC
Instead i have used` "typings install dt~es6-shim --global --save"`
Including `--global and dt~ before es6-shim`

**Comment by ricardosotogar** [comment] 2016-12-19 00:46
Doing this the problem is that the browser folder with the index.d.ts it is not created.  ¿?

**Comment by deeleman** [comment] 2016-12-19 11:11
Dupe of #10 

In any event, I'd advice you on installing typings from npm instead. You can find more infor at:

https://blogs.msdn.microsoft.com/typescript/2016/06/15/the-future-of-declaration-files/

**Closed as completed by deeleman** 2016-12-19 11:11 UTC
