### ISSUE TITLE
typings install es6-shim errors

### ISSUE THREAD

**Issue by webstudiopro** [deeleman/angular2-essentials#51] opened 2017-01-07 08:52 UTC
Hello,

While installing typings: 
$ typings install es6-shim --global --save  (--ambiant is deprecated)
I got next error messages:

typings ERR! message Unable to find "es6-shim" ("npm") in the registry.
typings ERR! message However, we found "es6-shim" for 1 other source: "dt"
typings ERR! message You can install these using the "source" option.
typings ERR! message We could use your help adding these typings to the registry: https://github.com/typings/registry
typings ERR! caused by https://api.typings.org/entries/npm/es6-shim/versions/latest responded with 404, expected it to equal 200
typings ERR! 
typings ERR! cwd /home/webstudiopro/Dev/angular/learning-angular
typings ERR! system Linux 4.4.0-45-generic
typings ERR! command "/usr/local/bin/node" "/usr/local/bin/typings" "install" "es6-shim" "--save"
typings ERR! node -v v6.0.0
typings ERR! typings -v 2.1.0

Any ideas? I'm using Ubuntu 14
Thx,
Fret Benny

**Comment by deeleman** [comment] 2017-01-07 11:57
Dupe of #10

In any event, I'd advice you on installing typings from npm instead. You can find more info at:

https://blogs.msdn.microsoft.com/typescript/2016/06/15/the-future-of-declaration-files/

**Closed as completed by deeleman** 2017-01-07 11:57 UTC
